language: ruby
cache: bundler
rvm: 
  - 2.3.1
addons:
  apt:
    packages:
    - libpq-dev
    - libmagickcore-dev
    - libmagickwand-dev
install:
  - gem install bundler
  - bundle install
script:
  - bundle exec rspec spec -fd
notifications:
  email: false

